<?php
/**
 * JournalApi
 * PHP version 5
 *
 * @category Class
 * @package  D4T\MT4Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Metatrader 4 Rest Api
 *
 * MetaTrader microservice. Call /init/ to get token, which is required in other methods.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mikha.dev@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace D4T\MT4Sdk\MT4Manager;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use D4T\MT4Sdk\ApiException;
use D4T\MT4Sdk\Configuration;
use D4T\MT4Sdk\HeaderSelector;
use D4T\MT4Sdk\ObjectSerializer;

/**
 * JournalApi Class Doc Comment
 *
 * @category Class
 * @package  D4T\MT4Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JournalApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation journalHistoryGet
     *
     * Get list of journal records
     *
     * @param  string $token Session token (required)
     * @param  float $mode Mode. (required)
     * @param  string $from Date From, Example: \&quot;from\&quot;&#x3D;\&quot;2019.02.12 00:00\&quot; (required)
     * @param  string $to Date To, Example: \&quot;to\&quot;&#x3D;\&quot;2019.02.12 00:00\&quot;. If empty current time is used. (required)
     * @param  string $filter Filter (optional)
     *
     * @throws \D4T\MT4Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \D4T\MT4Sdk\Models\ArrayOfJournalRecords
     */
    public function journalHistoryGet($token, $mode, $from, $to, $filter = null)
    {
        list($response) = $this->journalHistoryGetWithHttpInfo($token, $mode, $from, $to, $filter);
        return $response;
    }

    /**
     * Operation journalHistoryGetWithHttpInfo
     *
     * Get list of journal records
     *
     * @param  string $token Session token (required)
     * @param  float $mode Mode. (required)
     * @param  string $from Date From, Example: \&quot;from\&quot;&#x3D;\&quot;2019.02.12 00:00\&quot; (required)
     * @param  string $to Date To, Example: \&quot;to\&quot;&#x3D;\&quot;2019.02.12 00:00\&quot;. If empty current time is used. (required)
     * @param  string $filter Filter (optional)
     *
     * @throws \D4T\MT4Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \D4T\MT4Sdk\Models\ArrayOfJournalRecords, HTTP status code, HTTP response headers (array of strings)
     */
    public function journalHistoryGetWithHttpInfo($token, $mode, $from, $to, $filter = null)
    {
        $returnType = '\D4T\MT4Sdk\Models\ArrayOfJournalRecords';
        $request = $this->journalHistoryGetRequest($token, $mode, $from, $to, $filter);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\D4T\MT4Sdk\Models\ArrayOfJournalRecords',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\D4T\MT4Sdk\Models\ReturnType',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation journalHistoryGetAsync
     *
     * Get list of journal records
     *
     * @param  string $token Session token (required)
     * @param  float $mode Mode. (required)
     * @param  string $from Date From, Example: \&quot;from\&quot;&#x3D;\&quot;2019.02.12 00:00\&quot; (required)
     * @param  string $to Date To, Example: \&quot;to\&quot;&#x3D;\&quot;2019.02.12 00:00\&quot;. If empty current time is used. (required)
     * @param  string $filter Filter (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function journalHistoryGetAsync($token, $mode, $from, $to, $filter = null)
    {
        return $this->journalHistoryGetAsyncWithHttpInfo($token, $mode, $from, $to, $filter)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation journalHistoryGetAsyncWithHttpInfo
     *
     * Get list of journal records
     *
     * @param  string $token Session token (required)
     * @param  float $mode Mode. (required)
     * @param  string $from Date From, Example: \&quot;from\&quot;&#x3D;\&quot;2019.02.12 00:00\&quot; (required)
     * @param  string $to Date To, Example: \&quot;to\&quot;&#x3D;\&quot;2019.02.12 00:00\&quot;. If empty current time is used. (required)
     * @param  string $filter Filter (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function journalHistoryGetAsyncWithHttpInfo($token, $mode, $from, $to, $filter = null)
    {
        $returnType = '\D4T\MT4Sdk\Models\ArrayOfJournalRecords';
        $request = $this->journalHistoryGetRequest($token, $mode, $from, $to, $filter);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'journalHistoryGet'
     *
     * @param  string $token Session token (required)
     * @param  float $mode Mode. (required)
     * @param  string $from Date From, Example: \&quot;from\&quot;&#x3D;\&quot;2019.02.12 00:00\&quot; (required)
     * @param  string $to Date To, Example: \&quot;to\&quot;&#x3D;\&quot;2019.02.12 00:00\&quot;. If empty current time is used. (required)
     * @param  string $filter Filter (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function journalHistoryGetRequest($token, $mode, $from, $to, $filter = null)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling journalHistoryGet'
            );
        }
        // verify the required parameter 'mode' is set
        if ($mode === null || (is_array($mode) && count($mode) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $mode when calling journalHistoryGet'
            );
        }
        // verify the required parameter 'from' is set
        if ($from === null || (is_array($from) && count($from) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from when calling journalHistoryGet'
            );
        }
        // verify the required parameter 'to' is set
        if ($to === null || (is_array($to) && count($to) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $to when calling journalHistoryGet'
            );
        }

        $resourcePath = '/journal/history';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }
        // query params
        if ($mode !== null) {
            $queryParams['mode'] = ObjectSerializer::toQueryValue($mode);
        }
        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to);
        }
        // query params
        if ($filter !== null) {
            $queryParams['filter'] = ObjectSerializer::toQueryValue($filter);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
