<?php
/**
 * GroupSecuritiesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MetaTrader microservice
 *
 * MetaTrader microservice. Call <a href='#/paths/~1init~1/get'>/init/</a> to get token, which is required in other methods.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@dev4traders.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GroupSecuritiesTest Class Doc Comment
 *
 * @category    Class
 * @description GroupSecurities
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GroupSecuritiesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GroupSecurities"
     */
    public function testGroupSecurities()
    {
    }

    /**
     * Test attribute "trade"
     */
    public function testPropertyTrade()
    {
    }

    /**
     * Test attribute "execution"
     */
    public function testPropertyExecution()
    {
    }

    /**
     * Test attribute "comm_base"
     */
    public function testPropertyCommBase()
    {
    }

    /**
     * Test attribute "comm_type"
     */
    public function testPropertyCommType()
    {
    }

    /**
     * Test attribute "comm_lots"
     */
    public function testPropertyCommLots()
    {
    }

    /**
     * Test attribute "comm_agent"
     */
    public function testPropertyCommAgent()
    {
    }

    /**
     * Test attribute "comm_agent_type"
     */
    public function testPropertyCommAgentType()
    {
    }

    /**
     * Test attribute "spread_diff"
     */
    public function testPropertySpreadDiff()
    {
    }

    /**
     * Test attribute "lot_min"
     */
    public function testPropertyLotMin()
    {
    }

    /**
     * Test attribute "lot_max"
     */
    public function testPropertyLotMax()
    {
    }

    /**
     * Test attribute "lot_step"
     */
    public function testPropertyLotStep()
    {
    }
}
