<?php
/**
 * TradeTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  D4T\MT4Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Metatrader 4 Rest Api
 *
 * MetaTrader microservice. Call /init/ to get token, which is required in other methods.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mikha.dev@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace D4T\MT4Sdk;

/**
 * TradeTypeTest Class Doc Comment
 *
 * @category    Class
 * @description TradeType
 * @package     D4T\MT4Sdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TradeTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TradeType"
     */
    public function testTradeType()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }

    /**
     * Test attribute "symbol"
     */
    public function testPropertySymbol()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "type_str"
     */
    public function testPropertyTypeStr()
    {
    }

    /**
     * Test attribute "ticket"
     */
    public function testPropertyTicket()
    {
    }

    /**
     * Test attribute "login"
     */
    public function testPropertyLogin()
    {
    }

    /**
     * Test attribute "profit"
     */
    public function testPropertyProfit()
    {
    }

    /**
     * Test attribute "digits"
     */
    public function testPropertyDigits()
    {
    }

    /**
     * Test attribute "sl"
     */
    public function testPropertySl()
    {
    }

    /**
     * Test attribute "tp"
     */
    public function testPropertyTp()
    {
    }

    /**
     * Test attribute "pips"
     */
    public function testPropertyPips()
    {
    }

    /**
     * Test attribute "volume"
     */
    public function testPropertyVolume()
    {
    }

    /**
     * Test attribute "lots"
     */
    public function testPropertyLots()
    {
    }

    /**
     * Test attribute "swap"
     */
    public function testPropertySwap()
    {
    }

    /**
     * Test attribute "commission"
     */
    public function testPropertyCommission()
    {
    }

    /**
     * Test attribute "open_price"
     */
    public function testPropertyOpenPrice()
    {
    }

    /**
     * Test attribute "close_price"
     */
    public function testPropertyClosePrice()
    {
    }

    /**
     * Test attribute "open_time"
     */
    public function testPropertyOpenTime()
    {
    }

    /**
     * Test attribute "close_time"
     */
    public function testPropertyCloseTime()
    {
    }

    /**
     * Test attribute "open_time_str"
     */
    public function testPropertyOpenTimeStr()
    {
    }

    /**
     * Test attribute "close_time_str"
     */
    public function testPropertyCloseTimeStr()
    {
    }
}
