<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MetaTrader microservice
 *
 * MetaTrader microservice. Call <a href='#/paths/~1init~1/get'>/init/</a> to get token, which is required in other methods.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@dev4traders.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for checkUser
     *
     * Check user exists.
     *
     */
    public function testCheckUser()
    {
    }

    /**
     * Test case for deleteUser
     *
     * Delete user.
     *
     */
    public function testDeleteUser()
    {
    }

    /**
     * Test case for updateUser
     *
     * Update user.
     *
     */
    public function testUpdateUser()
    {
    }

    /**
     * Test case for userAddPost
     *
     * Create user.
     *
     */
    public function testUserAddPost()
    {
    }

    /**
     * Test case for userAuthPost
     *
     * Get user by credentials.
     *
     */
    public function testUserAuthPost()
    {
    }

    /**
     * Test case for userDepositPost
     *
     * Deposit account.
     *
     */
    public function testUserDepositPost()
    {
    }

    /**
     * Test case for userMarginUserLoginGet
     *
     * Get margin by user login.
     *
     */
    public function testUserMarginUserLoginGet()
    {
    }

    /**
     * Test case for userResetPwdPost
     *
     * Reset password.
     *
     */
    public function testUserResetPwdPost()
    {
    }

    /**
     * Test case for userUserLoginGet
     *
     * Get user by user login.
     *
     */
    public function testUserUserLoginGet()
    {
    }

    /**
     * Test case for userWithdrawPost
     *
     * Withdraw account.
     *
     */
    public function testUserWithdrawPost()
    {
    }

    /**
     * Test case for usersBulkAddPost
     *
     * Create users.
     *
     */
    public function testUsersBulkAddPost()
    {
    }

    /**
     * Test case for usersGet
     *
     * Get list of all users.
     *
     */
    public function testUsersGet()
    {
    }

    /**
     * Test case for usersOnlineGet
     *
     * Get list of online users.
     *
     */
    public function testUsersOnlineGet()
    {
    }
}
